### ISSUE TITLE
Can't place down anything from Prefab

### ISSUE THREAD

**Issue by TheBadMan25** [Brian-Wuest/MC-Prefab-Fabric#5]
On Fabric 0.11.3-1.16.5
Prefab 1.02 and 1.01 load fine, but latest 1.03 does not. It starts with a crash.
I have tried running it with nothing else loaded but the necessary "mods"
Java Hotspot 64-bit server VM
Minecraft
Mod Menu Client 1.14.13+build.19
Prefab 

I can run these in single player no problem, but in server it doesn't allow me to place/create the buildings. They appear just fine in the inventory, but just can't place. It pops up with the preview and the pre build option but once you click build nothing happens. This happens in both Forge and Fabric.
If you can help in any way that would be great!

**Comment by Brian-Wuest** [comment]
Make sure you are using the latest Fabric API Version (0.32.0+1.16).

That version of Mod Menu is no longer supported either. I will update the version page since I didn't see it loading for me on that version of Fabric.

In addition; from the mod list you provided it appears that you are missing the "Auto Config Updated API" mod. This has a mod file of "autoconfig1u-3.3.1". This file will be required on Server and Client side. Mod Menu will only be required on the Client side.

**Comment by TheBadMan25** [comment]
I apologize I thought I had to just download fabric and then prefab. I also don't know where I got my previous version of fabric and it wasn't the most up to date one like you had (strange). I also got it to not crash when booting thanks to your suggestions above. Also other note, since I downloaded the updates and the suggestions everything runs so much smoother now. Sorry I didn't know the other files were required. I guess I needed it as clear as black and white, thank you once again. <3

EDIT: I got everything to work now. I set up the Fabric Sever with all the necessary mod files and it works well. Do you know if this will work with Optifabric? I miss my visuals.

**Comment by Brian-Wuest** [comment]
I am not sure, if that is just a wrapper around optifine it should work but I believe that some things in prefab are disabled when optifine is discovered. I believe the preview feature is disabled or at least reduced when optifine is loaded.

Closing issue.
