### ISSUE TITLE
[Bug]: Recipes no longer working.

### ISSUE THREAD

**Issue by devRookie** [Brian-Wuest/MC-Prefab-Fabric#63]
### Minecraft Version

1.18.2

### Fabric Version

0.13.3

### Mod Version

3.1.2

### Details

Recipes do not seem to work. All dependencies are updated to the requirements. I have all of these items and it won't complete the build. I've also looked at the wiki to follow that recipe, no luck. I tested it with Aqua base and no luck as well. 

![2022-04-13_20 43 22](https://user-images.githubusercontent.com/8508007/163310377-a210d288-a576-45dc-a762-e5fbc5c7362d.png)
![2022-04-13_20 52 29](https://user-images.githubusercontent.com/8508007/163310451-639b915e-d87c-4f16-b8c3-f1e84057e41b.png)
![2022-04-13_20 53 57](https://user-images.githubusercontent.com/8508007/163310596-6ac775fe-d877-461e-9a5a-af9724404b6c.png)

**Comment by Brian-Wuest** [comment]
Looks like the new Fabric API broke recipes again.

**Comment by Brian-Wuest** [comment]
So, the wiki was out-of-date and probably has been for a LONG time.

I updated the wiki to be accurate.

However, the issue with REI is due to me using tags for recipes.

Because of the timing of loading recipes it doesn't know that certain items exist anymore with the 1.18.2 release of Minecraft as they changed a LOT of tagging stuff in that release.

REI will have to fix their issues in order for the recipe to load correctly.

In either way I updated the wiki to have the correct recipe.
